# Generated by Django 4.0.5 on 2022-06-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Number', models.IntegerField()),
                ('Amount_Paid', models.CharField(max_length=100)),
                ('Occupant_Name', models.CharField(max_length=100)),
                ('Occupant_Email', models.EmailField(max_length=100)),
                ('Occupant_Occupation', models.CharField(max_length=100)),
                ('Number_Of_Nights', models.IntegerField()),
                ('Start_Date', models.DateTimeField()),
                ('End_Date', models.DateTimeField()),
            ],
        ),
    ]
