# Generated by Django 4.0.5 on 2022-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_hotel', '0002_alter_management_occupant_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='Occupant_Name',
        ),
        migrations.AddField(
            model_name='management',
            name='Occupant_First_Name',
            field=models.CharField(default=(), max_length=100),
        ),
        migrations.AddField(
            model_name='management',
            name='Occupant_Last_Name',
            field=models.CharField(default=(), max_length=100),
        ),
    ]
