# Generated by Django 4.0.5 on 2022-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_hotel', '0003_remove_management_occupant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='Occupant_First_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='management',
            name='Occupant_Last_Name',
            field=models.CharField(max_length=100),
        ),
    ]
